services:
  mongodb:
    image: mongo:latest
    container_name: rfq-mongodb
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: rfq-mongo-express
    restart: always

    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123

    depends_on:
      - mongodb

  backend:
    build: ./backend
    container_name: rfq-backend
    restart: always

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - mongodb

volumes:
  mongodb_data: